### PR TITLE
GW Styling applied to both pages

### PR DESCRIPTION
**Pull request by maxturer**
Here's what this does:
- Incorporates styles & variables based on GW LAI profile
- Adds assets (fonts and logos)
- Restructures HTML to fit in new styling
- Adds CSS loading animation to download page

Let me know if that's enough styling for this purpose! My impression was that the E-Reserves Links page should stay minimally styled, but feel free to correct me on that if needed.
Both pages are functionally responsive for vertical orientations, but don't have a separate mobile design.

### CODE REVIEW

**Review by dolsysmith — APPROVED** [review]
It looks great! One thing I'm now wondering is whether it would be better to say "Your download has begun -- please check your computer's Downloads folder for {file name}" as opposed to "Your download will begin shortly," since the download happens but the animation keeps going, which may lead users to think the download hasn't started yet? 

But the styling is brilliant -- thank you!

**Comment by maxturer** [comment]
I can do that! The JS used to trigger the download is not in this repo, though, correct? 
I can set an empty paragraph element with an ID, then in the working script, the `innerHTML` of that ID could be set to the file name of the downloading file. Would that work?

**Comment by dolsysmith** [comment]
The JS is in `download.js`. It's very simple -- feel free to change it however you see fit. It's main function is to rewrite the URL parameters as a redirect URL to the actual file requested.

**Comment by dolsysmith** [comment]
Sorry - I hadn't realized that the JS files were missing. I've added them now. To test with the JS, you can put a PDF or some other binary-type file in the `custom-assets` folder, then run a simple web server from the command line within that folder (I use `python3 -m http.server`), and then visit the site with a URL like this: `http://localhost:8000/?file=file-to-download.pdf`.

**Comment by maxturer** [comment]
Took your advice! I also added some simple JS placeholders to the file list.

**Comment by dolsysmith** [comment]
Thanks, that looks great! I had to make one small change -- as currently configured on S3, everything that's not an actual reserves file lives at the root folder; the `custom-assets` folder is just an artifact of the GitHub repo. I can reorganize things on S3 if you think that would be better in the long run.

**Comment by maxturer** [comment]
All good, thanks for catching that! I forgot to revert that change, I only made it for testing.
I'll go ahead and merge these, then.

**Pull request merged**
